version: 0.2
phases:
 pre_build:
  commands:
   - echo Logging in to Amazon ECR...
   - aws --version
   - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 876690758121.dkr.ecr.us-east-1.amazonaws.com
   - REPOSITORY_URI=876690758121.dkr.ecr.us-east-1.amazonaws.com/fsm-repository
   - echo "The current build ID is $CODEBUILD_BUILD_ID"
   - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
   - echo IMAGE_TAG $IMAGE_TAG 
  build:
   commands:
    - echo build started on 'date'
    - echo building the Jar file
    - echo REPOSITORY_URI:latest $REPOSITORY_URI:latest
    - echo docker tag  $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
    - mvn clean install
    - echo Building the Docker image..
    - docker build -t demo-h2-2 
    - docker tag demo-h2-2:latest 876690758121.dkr.ecr.us-east-1.amazonaws.com/fsm-repository:latest
    - docker images
 post_build:
   commands:
    - docker push 876690758121.dkr.ecr.us-east-1.amazonaws.com/fsm-repository:latest
      # - docker push $REPOSITORY_URI:$IMAGE_TAG
      #- echo Writing image definitions files...
    #Give your container name
    # - Docker_CONTAINER_NAME=sb-demo-ecfr-container
    #- printf '[{"name":"%s", "imageUri":"%s"}]' $Docker_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json 
    #- echo $Docker_CONTAINER_NAME
    #- echo printing imagedefinitions.json
    #- cat imagedefinitions.json
      # artifacts:
      #files:
      # - imagedefinitions.json
      #- target/demo-0.0.1-SNAPSHOT.jar
